// <auto-generated />
namespace Profile.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_client : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_client));
        
        string IMigrationMetadata.Id
        {
            get { return "201811021605088_update_client"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
